export const dummyTableData = [
  {
    ITM_CTC_ID: "BTBC-882-2024",
    supplier: "Chemical Supplies Inc.",
    soldToParty: "Constellation Energy",
    material: "Glycol - 2114",
    validityPeriod: "01/Jan/2024 to 31/Dec/2024",
    buyPrice: "$80/MT",
    sellPrice: "€90/MT",
    currency: "EUR",
    targetQuantity: "10,000",
    unit: "MT",
    status: "Active",
  },
  {
    ITM_CTC_ID: "BTBC-441-2023",
    supplier: "TechParts Manufacturing",
    soldToParty: "Pacific Fuels Ltd.",
    material: "Lens - XJ720",
    validityPeriod: "01/Jan/2024 to 31/Dec/2024",
    buyPrice: "$80/MT",
    sellPrice: "€90/MT",
    currency: "EUR",
    targetQuantity: "12,000",
    unit: "MT",
    status: "Pending Approval",
  },
  {
    ITM_CTC_ID: "BTBC-775-2022",
    supplier: "Tital Steel Co.",
    soldToParty: "Orion Metals Inc.",
    material: "Steel",
    validityPeriod: "01/Jan/2024 to 31/Dec/2024",
    buyPrice: "$80/MT",
    sellPrice: "€90/MT",
    currency: "EUR",
    targetQuantity: "80,000",
    unit: "MT",
    status: "Expired",
  },
  {
    ITM_CTC_ID: "BTBC-441-2023",
    supplier: "TechParts Manufacturing",
    soldToParty: "Baltic Trade Co.",
    material: "Camera Cabinet",
    validityPeriod: "01/Jan/2024 to 31/Dec/2024",
    buyPrice: "$80/MT",
    sellPrice: "€90/MT",
    currency: "EUR",
    targetQuantity: "53,000",
    unit: "MT",
    status: "Expiring Soon",
  },
];

// Dummy data source — in a real integration headerDetails/contractItems would come from the contract API response.
export const dummyContractData = {
  headerDetails: {
    ITM_CTC_CLIENT: "GTM",
    ITM_CTC_CONTRACT_TYPE: "Back-to-Back Supply",
    ITM_CTC_PERSON: "GTM273 - John Miller",
    ITM_CTC_DOC_DATE: "2024-01-01",
    ITM_CTC_VAL_FROM: "2024-01-01",
    ITM_CTC_VAL_TO: "",
    ITM_CTC_SUPPLIER: "Chemical Supplier AG",
    ITM_CTC_CUST: "Constellation Energy SA",
    ITM_CTC_PURCH_ORG: "1000 - Central Procurement",
    ITM_CTC_SALES_ORG: "1000 - Central Procurement",
    ITM_CTC_PURCH_GRP: "PG1 - Steel Commodities",
    ITM_CTC_DIST_CH: "10 - Direct Sales",
    ITM_CTC_REF_NO: "",
    ITM_CTC_COUNTER_PARTY_REF_NO: "",
    ITM_CTC_PURCH_CUR: "EUR",
    ITM_CTC_SALES_CUR: "EUR",
    ITM_CTC_SUP_ACC_NO: "",
    ITM_CTC_CUST_REF: "",
    ITM_CTC_PURCH_INCO: "FOB",
    ITM_CTC_PURCH_INCO_LOC: "Al-Jubail",
    ITM_CTC_SALES_INCO: "FOB",
    ITM_CTC_SALES_INCO_LOC: "Ludwigshafen",
    ITM_CTC_TERMS_OF_PAY: "N30",
    ITM_CTC_TERMS_OF_PAY_SELL: "N30",
    ITM_CTC_EXC_RATE_TYPE: "M - Market",
    ITM_CTC_EXC_RATE_DATE: "2024-01-01",
    ITM_CTC_FIXED_EXC_RATE: "No",
    ITM_CTC_NOTES: "",
  },
  contractItems: [
    {
      material: "Glycol - 2114",
      targetQuantity: "10000",
      unit: "MT",
      buyPrice: "80",
      sellPrice: "50",
    },
  ],
};