export const dummyTableData = [
  {
    ITM_CTC_ID: "BTBC-882-2024",
    supplier: "Chemical Supplies Inc.",
    purchaseOrg: "1000 - Central Procurement",
    purchaseGroup: "PG1 - Steel Commodities",
    customer: "Constellation Energy",
    salesOrg: "1000 - Central Procurement",
    distChannel: "10 - Direct Sales",
    division: "20 - Chemicals",
    counterpartyRefNo: "CUST-REF-882",
    validityPeriod: "01/Jan/2024 to 31/Dec/2024",
    status: "Draft",
    purchasingCurrency: "EUR",
    purchaseIncoterms: "CIF - Hamburg Port",
    purchaseIncotermsLocation: "Al-Jubail",
    purchasePaymentTerms: "N30",
    salesCurrency: "EUR",
    salesIncoterms: "FOB - Rotterdam Port",
    salesIncotermsLocation: "Ludwigshafen",
    salesPaymentTerms: "N30",
    personResponsible: "John Miller",
    exchangeRateType: "M - Standard",
    documentDate: "01/Jan/2024",
    taxCode: "TX-001",
    material: [
      {
        contractItemId: "BTBC-882-2024-1",
        contractId: "BTBC-882-2024",
        supplier: "BASF",
        material: "Glycol - 2114",
        deliveryPeriodFrom: "2024-01-01",
        deliveryPeriodTo: "2024-12-31",
        salesQuantity: "10000",
        salesQuantityUnit: "MT",
        salesOverdeliveryTolerance: "5",
        salesUnderdeliveryTolerance: "5",
        purchaseQuantity: "10000",
        purchaseQuantityUnit: "MT",
        purchaseOverdeliveryTolerance: "5",
        purchaseUnderdeliveryTolerance: "5",
        salesPrice: "90",
        salesPriceCurrency: "EUR",
        salesPricePerUnit: "MT",
        purchasePrice: "80",
        purchasePriceCurrency: "USD",
        purchasePricePerUnit: "MT",
        plant: "PL01",
        storageLocation: "SL-100",
        expenses: [
          {
            expenseId: "BTBC-882-2024-1-1",
            expenseName: "Freight Costs",
            expenseAmount: "1000",
            expenseCurrency: "EUR",
            expensePer: "MT",
          },
          {
            expenseId: "BTBC-882-2024-1-2",
            expenseName: "Customs Duty",
            expenseAmount: "1000",
            expenseCurrency: "USD",
            expensePer: "MT",
          },
        ],
      },
      {
        contractItemId: "BTBC-882-2024-2",
        contractId: "BTBC-882-2024",
        supplier: "Lenskart",
        material: "Lens - XJ720",
        deliveryPeriodFrom: "2024-02-01",
        deliveryPeriodTo: "2024-11-30",
        salesQuantity: "5000",
        salesQuantityUnit: "PC",
        salesOverdeliveryTolerance: "3",
        salesUnderdeliveryTolerance: "3",
        purchaseQuantity: "5000",
        purchaseQuantityUnit: "PC",
        purchaseOverdeliveryTolerance: "3",
        purchaseUnderdeliveryTolerance: "3",
        salesPrice: "12",
        salesPriceCurrency: "EUR",
        salesPricePerUnit: "PC",
        purchasePrice: "9",
        purchasePriceCurrency: "USD",
        purchasePricePerUnit: "PC",
        plant: "PL02",
        storageLocation: "SL-200",
        expenses: [],
      },
    ],
    fixedExchangeRate: true,
    netQuantity: "15,000",
    netQuantityUnit: "MT",
    netSalesValue: "$1,350,000",
    salesValueCurrency: "USD",
    netPurchaseValue: "$1,200,000",
    purchaseValueCurrency: "USD",
    totalExpenses: "$50,000",
    totalContractValue: "$1,400,000",
  },
  {
    ITM_CTC_ID: "BTBC-441-2023",
    supplier: "TechParts Manufacturing",
    customer: "Pacific Fuels Ltd.",
    salesOrg: "1000 - Central Procurement",
    distChannel: "10 - Direct Sales",
    division: "20 - Chemicals",
    counterpartyRefNo: "CUST-REF-441",
    validityPeriod: "01/Jan/2024 to 31/Dec/2024",
    status: "Approval Pending",
    personResponsible: "Sarah Connors",
    purchaseOrg: "1200 - Electronics Procurement",
    purchaseGroup: "PG2 - Electronics Commodities",
    exchangeRateType: "M - Standard",
    documentDate: "15/Mar/2023",
    purchasingCurrency: "USD",
    purchaseIncoterms: "CIF - Hamburg Port",
    purchaseIncotermsLocation: "Al-Jubail",
    purchasePaymentTerms: "N45",
    salesCurrency: "USD",
    salesIncoterms: "FOB - Rotterdam Port",
    salesIncotermsLocation: "Ludwigshafen",
    salesPaymentTerms: "N45",
    material: [
      {
        contractItemId: "BTBC-441-2023-1",
        contractId: "BTBC-441-2023",
        supplier: "BASF",
        material: "Glycol - 2114",
        deliveryPeriodFrom: "2024-01-01",
        deliveryPeriodTo: "2024-12-31",
        salesQuantity: "12000",
        salesQuantityUnit: "MT",
        salesOverdeliveryTolerance: "5",
        salesUnderdeliveryTolerance: "5",
        purchaseQuantity: "12000",
        purchaseQuantityUnit: "MT",
        purchaseOverdeliveryTolerance: "5",
        purchaseUnderdeliveryTolerance: "5",
        salesPrice: "90",
        salesPriceCurrency: "EUR",
        salesPricePerUnit: "MT",
        purchasePrice: "80",
        purchasePriceCurrency: "USD",
        purchasePricePerUnit: "MT",
        plant: "PL01",
        storageLocation: "SL-100",
        expenses: [],
      },
      {
        contractItemId: "BTBC-441-2023-2",
        contractId: "BTBC-441-2023",
        supplier: "Sony",
        material: "Camera Cabinet",
        deliveryPeriodFrom: "2024-04-01",
        deliveryPeriodTo: "2024-09-30",
        salesQuantity: "2000",
        salesQuantityUnit: "PC",
        salesOverdeliveryTolerance: "2",
        salesUnderdeliveryTolerance: "2",
        purchaseQuantity: "2000",
        purchaseQuantityUnit: "PC",
        purchaseOverdeliveryTolerance: "2",
        purchaseUnderdeliveryTolerance: "2",
        salesPrice: "45",
        salesPriceCurrency: "EUR",
        salesPricePerUnit: "PC",
        purchasePrice: "35",
        purchasePriceCurrency: "USD",
        purchasePricePerUnit: "PC",
        plant: "PL01",
        storageLocation: "SL-100",
        expenses: [],
      },
      {
        contractItemId: "BTBC-441-2023-3",
        contractId: "BTBC-441-2023",
        supplier: "Lenskart",
        material: "Lens - XJ720",
        deliveryPeriodFrom: "2024-01-01",
        deliveryPeriodTo: "2024-12-31",
        salesQuantity: "12000",
        salesQuantityUnit: "MT",
        salesOverdeliveryTolerance: "5",
        salesUnderdeliveryTolerance: "5",
        purchaseQuantity: "12000",
        purchaseQuantityUnit: "MT",
        purchaseOverdeliveryTolerance: "5",
        purchaseUnderdeliveryTolerance: "5",
        salesPrice: "90",
        salesPriceCurrency: "EUR",
        salesPricePerUnit: "MT",
        purchasePrice: "80",
        purchasePriceCurrency: "USD",
        purchasePricePerUnit: "MT",
        plant: "PL02",
        storageLocation: "SL-200",
        expenses: [],
      },
      {
        contractItemId: "BTBC-441-2023-4",
        contractId: "BTBC-441-2023",
        supplier: "Tata Steel",
        material: "Steel",
        deliveryPeriodFrom: "2024-03-01",
        deliveryPeriodTo: "2024-10-31",
        salesQuantity: "15000",
        salesQuantityUnit: "MT",
        salesOverdeliveryTolerance: "5",
        salesUnderdeliveryTolerance: "5",
        purchaseQuantity: "15000",
        purchaseQuantityUnit: "MT",
        purchaseOverdeliveryTolerance: "5",
        purchaseUnderdeliveryTolerance: "5",
        salesPrice: "550",
        salesPriceCurrency: "GBP",
        salesPricePerUnit: "MT",
        purchasePrice: "480",
        purchasePriceCurrency: "USD",
        purchasePricePerUnit: "MT",
        plant: "PL03",
        storageLocation: "SL-300",
        expenses: [],
      },
    ],
    taxCode: "TX-001",
    fixedExchangeRate: false,
    netQuantity: "15,000",
    netQuantityUnit: "MT",
    netSalesValue: "$1,350,000",
    salesValueCurrency: "USD",
    netPurchaseValue: "$1,200,000",
    purchaseValueCurrency: "USD",
    totalExpenses: "$50,000",
    totalContractValue: "$1,400,000",
  },
  {
    ITM_CTC_ID: "BTBC-775-2022",
    supplier: "Tital Steel Co.",
    customer: "Orion Metals Inc.",
    salesOrg: "1000 - Central Procurement",
    distChannel: "10 - Direct Sales",
    division: "20 - Chemicals",
    counterpartyRefNo: "CUST-REF-775",
    validityPeriod: "01/Jan/2024 to 31/Dec/2024",
    status: "Approved",
    personResponsible: "David Okafor",
    purchaseOrg: "1300 - Metals Procurement",
    purchaseGroup: "PG3 - Metals Commodities",
    exchangeRateType: "G - Spot",
    documentDate: "10/Feb/2022",
    purchasingCurrency: "USD",
    purchaseIncoterms: "CIF - Hamburg Port",
    purchaseIncotermsLocation: "Al-Jubail",
    purchasePaymentTerms: "N30",
    salesCurrency: "USD",
    salesIncoterms: "FOB - Rotterdam Port",
    salesIncotermsLocation: "Ludwigshafen",
    salesPaymentTerms: "N60",
    material: [
      {
        contractItemId: "BTBC-775-2022-1",
        contractId: "BTBC-775-2022",
        supplier: "Tata Steel",
        material: "Steel",
        deliveryPeriodFrom: "2024-01-01",
        deliveryPeriodTo: "2024-12-31",
        salesQuantity: "80000",
        salesQuantityUnit: "MT",
        salesOverdeliveryTolerance: "5",
        salesUnderdeliveryTolerance: "5",
        purchaseQuantity: "80000",
        purchaseQuantityUnit: "MT",
        purchaseOverdeliveryTolerance: "5",
        purchaseUnderdeliveryTolerance: "5",
        salesPrice: "90",
        salesPriceCurrency: "EUR",
        salesPricePerUnit: "MT",
        purchasePrice: "80",
        purchasePriceCurrency: "USD",
        purchasePricePerUnit: "MT",
        plant: "PL03",
        storageLocation: "SL-300",
        expenses: [],
      },
      {
        contractItemId: "BTBC-775-2022-2",
        contractId: "BTBC-775-2022",
        supplier: "Sony",
        material: "Camera Cabinet",
        deliveryPeriodFrom: "2024-04-01",
        deliveryPeriodTo: "2024-09-30",
        salesQuantity: "2000",
        salesQuantityUnit: "PC",
        salesOverdeliveryTolerance: "2",
        salesUnderdeliveryTolerance: "2",
        purchaseQuantity: "2000",
        purchaseQuantityUnit: "PC",
        purchaseOverdeliveryTolerance: "2",
        purchaseUnderdeliveryTolerance: "2",
        salesPrice: "45",
        salesPriceCurrency: "EUR",
        salesPricePerUnit: "PC",
        purchasePrice: "35",
        purchasePriceCurrency: "USD",
        purchasePricePerUnit: "PC",
        plant: "PL01",
        storageLocation: "SL-100",
        expenses: [],
      },
    ],
    taxCode: "TX-001",
    fixedExchangeRate: true,
    netQuantity: "82,000",
    netQuantityUnit: "MT",
    netSalesValue: "$1,350,000",
    salesValueCurrency: "USD",
    netPurchaseValue: "$1,200,000",
    purchaseValueCurrency: "USD",
    totalExpenses: "$50,000",
    totalContractValue: "$1,400,000",
  },
  {
    ITM_CTC_ID: "BTBC-963-2023",
    supplier: "TechParts Manufacturing",
    customer: "Baltic Trade Co.",
    salesOrg: "1000 - Central Procurement",
    distChannel: "10 - Direct Sales",
    division: "20 - Chemicals",
    counterpartyRefNo: "CUST-REF-963",
    validityPeriod: "01/Jan/2024 to 31/Dec/2024",
    status: "Orders Created",
    personResponsible: "Maria Lindqvist",
    purchaseOrg: "1200 - Electronics Procurement",
    purchaseGroup: "PG2 - Electronics Commodities",
    exchangeRateType: "M - Standard",
    documentDate: "22/Jun/2023",
    purchasingCurrency: "USD",
    purchaseIncoterms: "CIF - Hamburg Port",
    purchaseIncotermsLocation: "Al-Jubail",
    purchasePaymentTerms: "N30",
    salesCurrency: "EUR",
    salesIncoterms: "FOB - Rotterdam Port",
    salesIncotermsLocation: "Ludwigshafen",
    salesPaymentTerms: "N30",
    material: [
      {
        contractItemId: "BTBC-963-2023-1",
        contractId: "BTBC-963-2023",
        supplier: "Sony",
        material: "Camera Cabinet",
        deliveryPeriodFrom: "2024-01-01",
        deliveryPeriodTo: "2024-12-31",
        salesQuantity: "53000",
        salesQuantityUnit: "MT",
        salesOverdeliveryTolerance: "5",
        salesUnderdeliveryTolerance: "5",
        purchaseQuantity: "53000",
        purchaseQuantityUnit: "MT",
        purchaseOverdeliveryTolerance: "5",
        purchaseUnderdeliveryTolerance: "5",
        salesPrice: "90",
        salesPriceCurrency: "EUR",
        salesPricePerUnit: "MT",
        purchasePrice: "80",
        purchasePriceCurrency: "USD",
        purchasePricePerUnit: "MT",
        plant: "PL02",
        storageLocation: "SL-200",
        expenses: [],
      },
      {
        contractItemId: "BTBC-963-2023-2",
        contractId: "BTBC-963-2023",
        supplier: "BASF",
        material: "Glycol - 2114",
        deliveryPeriodFrom: "2024-05-01",
        deliveryPeriodTo: "2024-08-31",
        salesQuantity: "6000",
        salesQuantityUnit: "L",
        salesOverdeliveryTolerance: "5",
        salesUnderdeliveryTolerance: "5",
        purchaseQuantity: "6000",
        purchaseQuantityUnit: "L",
        purchaseOverdeliveryTolerance: "5",
        purchaseUnderdeliveryTolerance: "5",
        salesPrice: "6",
        salesPriceCurrency: "EUR",
        salesPricePerUnit: "L",
        purchasePrice: "5",
        purchasePriceCurrency: "USD",
        purchasePricePerUnit: "L",
        plant: "PL01",
        storageLocation: "SL-100",
        expenses: [],
      },
    ],
    taxCode: "TX-001",
    fixedExchangeRate: false,
    netQuantity: "59,000",
    netQuantityUnit: "MT",
    netSalesValue: "$1,350,000",
    salesValueCurrency: "USD",
    netPurchaseValue: "$1,200,000",
    purchaseValueCurrency: "USD",
    totalExpenses: "$50,000",
    totalContractValue: "$1,400,000",
  },
];

// Dummy data source — in a real integration headerDetails/contractItems would come from the contract API response.
export const dummyContractData = {
  headerDetails: {
    ITM_CTC_CLIENT: "GTM",
    ITM_CTC_CONTRACT_TYPE: "Back-to-Back Supply",
    ITM_CTC_PERSON: "GTM273 - John Miller",
    ITM_CTC_DOC_DATE: "2024-01-01",
    ITM_CTC_VAL_FROM: "2024-01-01",
    ITM_CTC_VAL_TO: "",
    ITM_CTC_SUPPLIER: "Chemical Supplier AG",
    ITM_CTC_CUST: "Constellation Energy SA",
    ITM_CTC_PURCH_ORG: "1000 - Central Procurement",
    ITM_CTC_SALES_ORG: "1000 - Central Procurement",
    ITM_CTC_PURCH_GRP: "PG1 - Steel Commodities",
    ITM_CTC_DIST_CH: "10 - Direct Sales",
    ITM_CTC_REF_NO: "",
    ITM_CTC_COUNTER_PARTY_REF_NO: "",
    ITM_CTC_PURCH_CUR: "EUR",
    ITM_CTC_SALES_CUR: "EUR",
    ITM_CTC_SUP_ACC_NO: "",
    ITM_CTC_CUST_REF: "",
    ITM_CTC_PURCH_INCO: "FOB",
    ITM_CTC_PURCH_INCO_LOC: "Al-Jubail",
    ITM_CTC_SALES_INCO: "FOB",
    ITM_CTC_SALES_INCO_LOC: "Ludwigshafen",
    ITM_CTC_TERMS_OF_PAY: "N30",
    ITM_CTC_TERMS_OF_PAY_SELL: "N30",
    ITM_CTC_EXC_RATE_TYPE: "M - Market",
    ITM_CTC_EXC_RATE_DATE: "2024-01-01",
    ITM_CTC_FIXED_EXC_RATE: "No",
    ITM_CTC_NOTES: "",
  },
  contractItems: [
    {
      supplier: "BASF",
      material: "Glycol - 2114",
      deliveryPeriodFrom: "2024-01-01",
      deliveryPeriodTo: "2024-12-31",
      salesQuantity: "10000",
      salesQuantityUnit: "MT",
      salesOverdeliveryTolerance: "5",
      salesUnderdeliveryTolerance: "5",
      purchaseQuantity: "10000",
      purchaseQuantityUnit: "MT",
      purchaseOverdeliveryTolerance: "5",
      purchaseUnderdeliveryTolerance: "5",
      salesPrice: "90",
      salesPriceCurrency: "EUR",
      salesPricePerUnit: "MT",
      purchasePrice: "80",
      purchasePriceCurrency: "USD",
      purchasePricePerUnit: "MT",
      plant: "PL01",
      storageLocation: "SL-100",
      expenses: [],
    },
  ],
};

export const B2BContractStatCards = [
  { label: "Contract Value", value: "€1.95M", sub: "up by 12% vs Last Year" },
  { label: "Total Contracts", value: "4", sub: "+2 this week" },
  { label: "Active Contracts", value: "12", sub: "Currently Operation" },
  { label: "Pending Approval", value: "4", sub: "Contracts Awaiting" },
  { label: "Expiring Soon", value: "3", sub: "Next 30 days" },
  { label: "Expired Contracts", value: "1", sub: "Action Required" },
];
export const B2BContractItemsStatCards = [
  { label: "Total Contract Items", value: "24", sub: "+5 this week" },
  { label: "Active Contract Items", value: "18", sub: "Currently Operation" },
  { label: "Pending Approval", value: "3", sub: "Items Awaiting" },
  { label: "Expiring Soon", value: "2", sub: "Next 30 days" },
  { label: "Expired Contract Items", value: "1", sub: "Action Required" },
];
export const tradingStatuses = [
  "Draft",
  "Approval Pending",
  "Approved",
  "Orders Created",
  "Posted to SAP",
  "Expired",
  "Cancelled",
];
