export const data = {
  0: {
    id: "row-6",
    supplier: "BASF",
    material: "Glycol - 2114",
    itemCategory: "Stock Shipment",
    salesQty: "10000",
    salesUnit: "MT",
    purchaseQty: "10000",
    purchaseUnit: "MT",
    buyPrice: "80",
    sellPrice: "50",
    priceUnit: "MT",
    plant: "PL01",
    storageLocation: "SL-100",
    deliveryDate: "",
  },
  ITM_CTC_CONTRACT_TYPE: {
    key: "b2bsupply",
    value: "Back to Back Supply",
  },
  ITM_CTC_PERSON: {
    key: "Gustavo Fring",
    value: "Gustavo Fring",
  },
  ITM_CTC_DATE: "2026-07-05T18:30:00.000Z",
  ITM_CTC_VAL_FROM: "2026-07-02T18:30:00.000Z",
  ITM_CTC_DOC_DATE: "2026-07-06T18:30:00.000Z",
  ITM_CTC_SUPPLIER_AGREED: false,
  ITM_CTC_VAL_TO: "2026-07-05T18:30:00.000Z",
  ITM_CTC_SUPPLIER: "sibasis",
  ITM_CTC_CUST: "sibasis",
  ITM_CTC_PURCH_ORG: "sibasis",
  ITM_CTC_SALES_ORG: "sibasis",
  ITM_CTC_PURCH_GRP: "sibasis",
  ITM_CTC_DIST_CH: "sibasis",
  ITM_CTC_REF_NO: "sibasis",
  ITM_CTC_COUNTER_PARTY_REF_NO: "sibasis",
  ITM_CTC_PURCH_CUR: "sibas",
  ITM_CTC_SALES_CUR: "sibas",
  ITM_CTC_SUP_ACC_NO: "sibasis",
  ITM_CTC_CUST_REF: "sibasis",
  ITM_CTC_PURCH_INCO: {
    key: "fob",
    value: "FOB",
  },
  ITM_CTC_PURCH_INCO_LOC: "sibasis",
  ITM_CTC_SALES_INCO: {
    key: "CFR",
    value: "CFR",
  },
  ITM_CTC_SALES_INCO_LOC: "sibasis",
  ITM_CTC_TAX_CODE: {
    key: "T007A",
    value: "T007A",
  },
  ITM_CTC_TERMS_OF_PAY: "sibasis",
  ITM_CTC_TERMS_OF_PAY_SELL: "sibasis",
  ITM_CTC_EXC_RATE_TYPE: "sibasis",
  ITM_CTC_EXC_RATE_DATE: "2026-07-06T18:30:00.000Z",
  ITM_CTC_FIXED_EXC_RATE: true,
  ITM_CTC_NOTES: "sibasis",
};
