import Checkbox from "@mui/material/Checkbox";

const applicationConfig = (t) => {
  const modules = [
    {
      moduleCode: "OR",
      moduleName: "Sales Order",
      createButtonText: "Create Order",
      listDataBinding: "aSalesOrderList",
      detailsDataBinding: "oSalesOrderDetails",
      moduleHeading: {
        en: "Sales Order",
        greek: "Parangelía pólisis",
      },
    },
    {
      moduleName: "Admin Console",
    },
  ];
  const moduleListFields = [
    {
      moduleName: "Sales Order",
      columnsList: [
        {
          fieldName: "Request ID",
          fieldBinding: "orderHeaderId",
          fieldLabel: t("RequestID"),
          type: "id",
          visible: true,
          pinned: false,
        },
        {
          fieldName: "SAP Order ID",
          fieldBinding: "sapOrderId",
          fieldLabel: t("sapOrderId"),
          type: "id",
          visible: true,
          pinned: false,
        },
        {
          fieldName: "PO Number",
          fieldBinding: "poNumber",
          fieldLabel: t("poNumber"),
          type: "poNumber",
          visible: true,
          pinned: false,
        },
        {
          fieldName: "Order Type",
          fieldBinding: "poType",
          fieldLabel: t("orderType"),
          type: "orderType",
          visible: true,
          pinned: false,
        },
        {
          fieldName: "Customer",
          fieldBinding: ["sapCustomerName", "sapCustomerId"],
          fieldLabel: t("customer"),
          type: "customer",
          visible: true,
          pinned: false,
        },
        {
          fieldName: "Created On",
          fieldBinding: "createdDate",
          fieldLabel: t("createdOn"),
          type: "date",
          visible: true,
          pinned: false,
        },
        {
          fieldName: "Req. Delivery Date",
          fieldBinding: "requestDeliveryDate",
          fieldLabel: t("reqDeliveryDate"),
          type: "reqdate",
          visible: false,
          pinned: false,
        },
        {
          fieldName: "Sender Email",
          fieldBinding: "senderEmail",
          fieldLabel: t("senderEmail") || "Sender Email",
          type: "email",
          visible: true,
          pinned: false,
        },
        {
          fieldName: "Success",
          fieldBinding: "successFlag",
          fieldLabel: t("Success"),
          visible: true,
          pinned: false,
          type: "successFlag",
        },
        {
          fieldName: "Exception Type",
          fieldBinding: "exceptionType",
          fieldLabel: t("exceptionType"),
          fieldLabel: "Exception Type",
          visible: true,
          pinned: false,
          type: "exceptionType",
        },
        {
          fieldName: "Status",
          fieldBinding: "docProcessStatus",
          fieldLabel: t("Status"),
          visible: true,
          pinned: false,
          type: "status",
        },

      ],
      itemDetailsList: {
        toBeReviewed: [
          {
            fieldName: "Icon",
            fieldBinding: "exceptionType",
            fieldLabel: "",
            type: "icons",
            visible: true,
            pinned: true,
          },
          {
            fieldName: "S.No",
            fieldBinding: "soItemNumber",
            fieldLabel: t("sNo"),
            type: "sNo",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Item Number",
            fieldBinding: "sapItemNumber",
            fieldLabel: t("sapItemNumber"),
            type: "sapItemNumber",
            visible: true,
            pinned: false,
          },

          {
            fieldName: "Material ID",
            fieldBinding: "poMaterialNumber",
            fieldLabel: t("customerMaterialId"),
            type: "poMaterialNumber",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Material Description",
            fieldBinding: "poMatDescription",
            fieldLabel: t("materialDescription"),
            type: "poMatDescription",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Material ID",
            fieldBinding: "sapMaterialNumber",
            fieldLabel: t("sapMaterialId"),
            type: "sapMaterialNumber",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Material Description",
            fieldBinding: "sapMatDescription",
            fieldLabel: t("sapMaterialDescription"),
            type: "sapMatDescription",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Quantity",
            fieldBinding: "sapQuantity",
            fieldLabel: t("sapQuantity"),
            type: "sapQuantity",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP Unit Price",
            fieldBinding: "sapUnitPrice",
            fieldLabel: "SAP Unit Price",
            type: "sapUnitPrice",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP Net Price",
            fieldBinding: "sapTotalAmount",
            fieldLabel: "SAP Net Price",
            type: "sapTotalPrice",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP UOM",
            fieldBinding: "sapUom",
            fieldLabel: t("sapUom"),
            fieldLabelKey: "sapUom",
            type: "sapUom",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "PO Quantity",
            fieldBinding: "poQuantity",
            fieldLabel: t("poQuantity"),
            type: "poQuantity",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Unit Price",
            fieldBinding: "poUnitPrice",
            fieldLabel: t("poUnitPrice"),
            type: "poUnitPrice",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Net Price",
            fieldBinding: "poTotalAmount",
            fieldLabel: t("poTotalAmount"),
            type: "poTotalAmount",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "PO UOM",
            fieldBinding: "poUom",
            fieldLabel: t("poUom"),
            type: "poUom",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Exception Type",
            fieldBinding: "exceptionType",
            fieldLabel: t("exceptionType"),
            type: "exceptionTypeButton",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Action",
            fieldBinding: "exceptionType",
            fieldLabel: t("action"),
            type: "action",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Edit",
            fieldBinding: "edit",
            fieldLabel: t("edit"),
            type: "edit",
            visible: true,
            pinned: false,
          },
        ],

        Created: [
          {
            fieldName: "Icon",
            fieldBinding: "exceptionType",
            fieldLabel: "",
            type: "icons",
            visible: true,
            pinned: true,
          },
          {
            fieldName: "S.No",
            fieldBinding: "soItemNumber",
            fieldLabel: t("sNo"),
            type: "sNo",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Item Number",
            fieldBinding: "sapItemNumber",
            fieldLabel: t("sapItemNumber"),
            type: "sapItemNumber",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Material ID",
            fieldBinding: "poMaterialNumber",
            fieldLabel: t("customerMaterialId"),
            type: "poMaterialNumber",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Material Description",
            fieldBinding: "poMatDescription",
            fieldLabel: t("materialDescription"),
            type: "poMatDescription",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Material ID",
            fieldBinding: "sapMaterialNumber",
            fieldLabel: t("sapMaterialId"),
            type: "sapMaterialNumber",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Material Description",
            fieldBinding: "sapMatDescription",
            fieldLabel: t("sapMaterialDescription"),
            type: "sapMatDescription",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Quantity",
            fieldBinding: "sapQuantity",
            fieldLabel: t("sapQuantity"),
            type: "sapQuantity",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP Unit Price",
            fieldBinding: "sapUnitPrice",
            fieldLabel: "SAP Unit Price",
            type: "sapUnitPrice",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP Net Price",
            fieldBinding: "sapTotalAmount",
            fieldLabel: "SAP Net Price",
            type: "sapTotalPrice",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP UOM",
            fieldBinding: "sapUom",
            fieldLabel: t("sapUom"),
            fieldLabelKey: "sapUom",
            type: "sapUom",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "PO Quantity",
            fieldBinding: "poQuantity",
            fieldLabel: t("poQuantity"),
            type: "poQuantity",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Unit Price",
            fieldBinding: "poUnitPrice",
            fieldLabel: t("poUnitPrice"),
            type: "poUnitPrice",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Net Price",
            fieldBinding: "poTotalAmount",
            fieldLabel: t("poTotalAmount"),
            type: "poTotalAmount",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "PO UOM",
            fieldBinding: "poUom",
            fieldLabel: t("poUom"),
            type: "poUom",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Exception Type",
            fieldBinding: "exceptionType",
            fieldLabel: t("exceptionType"),
            type: "exceptionTypeButton",
            visible: true,
            pinned: false,
          },
        ],

        Queued: [
          {
            fieldName: "Icon",
            fieldBinding: "exceptionType",
            fieldLabel: "",
            type: "icons",
            visible: true,
            pinned: true,
          },
          {
            fieldName: "S.No",
            fieldBinding: "soItemNumber",
            fieldLabel: t("sNo"),
            type: "sNo",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Item Number",
            fieldBinding: "sapItemNumber",
            fieldLabel: t("sapItemNumber"),
            type: "sapItemNumber",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Material ID",
            fieldBinding: "poMaterialNumber",
            fieldLabel: t("customerMaterialId"),
            type: "poMaterialNumber",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Material Description",
            fieldBinding: "poMatDescription",
            fieldLabel: t("materialDescription"),
            type: "poMatDescription",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Material ID",
            fieldBinding: "sapMaterialNumber",
            fieldLabel: t("sapMaterialId"),
            type: "sapMaterialNumber",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Material Description",
            fieldBinding: "sapMatDescription",
            fieldLabel: t("sapMaterialDescription"),
            type: "sapMatDescription",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Quantity",
            fieldBinding: "sapQuantity",
            fieldLabel: t("sapQuantity"),
            type: "sapQuantity",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP Unit Price",
            fieldBinding: "sapUnitPrice",
            fieldLabel: "SAP Unit Price",
            type: "sapUnitPrice",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP Net Price",
            fieldBinding: "sapTotalAmount",
            fieldLabel: "SAP Net Price",
            type: "sapTotalPrice",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP UOM",
            fieldBinding: "sapUom",
            fieldLabel: t("sapUom"),
            fieldLabelKey: "sapUom",
            type: "sapUom",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "PO Quantity",
            fieldBinding: "poQuantity",
            fieldLabel: t("poQuantity"),
            type: "poQuantity",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Unit Price",
            fieldBinding: "poUnitPrice",
            fieldLabel: t("poUnitPrice"),
            type: "poUnitPrice",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Net Price",
            fieldBinding: "poTotalAmount",
            fieldLabel: t("poTotalAmount"),
            type: "poTotalAmount",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "PO UOM",
            fieldBinding: "poUom",
            fieldLabel: t("poUom"),
            type: "poUom",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Exception Type",
            fieldBinding: "exceptionType",
            fieldLabel: t("exceptionType"),
            type: "exceptionTypeButton",
            visible: true,
            pinned: false,
          },
        ],

        createdWithBlock: [
          {
            fieldName: "Icon",
            fieldBinding: "exceptionType",
            fieldLabel: "",
            type: "icons",
            visible: true,
            pinned: true,
          },
          {
            fieldName: "S.No",
            fieldBinding: "soItemNumber",
            fieldLabel: t("sNo"),
            type: "sNo",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Item Number",
            fieldBinding: "sapItemNumber",
            fieldLabel: t("sapItemNumber"),
            type: "sapItemNumber",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Material ID",
            fieldBinding: "poMaterialNumber",
            fieldLabel: t("customerMaterialId"),
            type: "poMaterialNumber",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Material Description",
            fieldBinding: "poMatDescription",
            fieldLabel: t("materialDescription"),
            type: "poMatDescription",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Material ID",
            fieldBinding: "sapMaterialNumber",
            fieldLabel: t("sapMaterialId"),
            type: "sapMaterialNumber",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Material Description",
            fieldBinding: "sapMatDescription",
            fieldLabel: t("sapMaterialDescription"),
            type: "sapMatDescription",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Quantity",
            fieldBinding: "sapQuantity",
            fieldLabel: t("sapQuantity"),
            type: "sapQuantity",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP Unit Price",
            fieldBinding: "sapUnitPrice",
            fieldLabel: "SAP Unit Price",
            type: "sapUnitPrice",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP Net Price",
            fieldBinding: "sapTotalAmount",
            fieldLabel: "SAP Net Price",
            type: "sapTotalPrice",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP UOM",
            fieldBinding: "sapUom",
            fieldLabel: t("sapUom"),
            fieldLabelKey: "sapUom",
            type: "sapUom",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "PO Quantity",
            fieldBinding: "poQuantity",
            fieldLabel: t("poQuantity"),
            type: "poQuantity",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Unit Price",
            fieldBinding: "poUnitPrice",
            fieldLabel: t("poUnitPrice"),
            type: "poUnitPrice",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Net Price",
            fieldBinding: "poTotalAmount",
            fieldLabel: t("poTotalAmount"),
            type: "poTotalAmount",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "PO UOM",
            fieldBinding: "poUom",
            fieldLabel: t("poUom"),
            type: "poUom",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Exception Type",
            fieldBinding: "exceptionType",
            fieldLabel: t("exceptionType"),
            type: "exceptionTypeButton",
            visible: true,
            pinned: false,
          },
        ],

        Cancelled: [
          {
            fieldName: "Icon",
            fieldBinding: "exceptionType",
            fieldLabel: "",
            type: "icons",
            visible: true,
            pinned: true,
          },
          {
            fieldName: "S.No",
            fieldBinding: "soItemNumber",
            fieldLabel: t("sNo"),
            type: "sNo",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Item Number",
            fieldBinding: "sapItemNumber",
            fieldLabel: t("sapItemNumber"),
            type: "sapItemNumber",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Material ID",
            fieldBinding: "poMatNum",
            fieldLabel: t("customerMaterialId"),
            type: "poMatNum",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Material Description",
            fieldBinding: "poMatDescription",
            fieldLabel: t("materialDescription"),
            type: "poMatDescription",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Material ID",
            fieldBinding: "sapMaterialNumber",
            fieldLabel: t("sapMaterialId"),
            type: "sapMaterialNumber",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Material Description",
            fieldBinding: "sapMatDescription",
            fieldLabel: t("sapMaterialDescription"),
            type: "sapMatDescription",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Quantity",
            fieldBinding: "sapQuantity",
            fieldLabel: t("sapQuantity"),
            type: "sapQuantity",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP Unit Price",
            fieldBinding: "sapUnitPrice",
            fieldLabel: "SAP Unit Price",
            type: "sapUnitPrice",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP Net Price",
            fieldBinding: "sapTotalAmount",
            fieldLabel: "SAP Net Price",
            type: "sapTotalPrice",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP UOM",
            fieldBinding: "sapUom",
            fieldLabel: t("sapUom"),
            fieldLabelKey: "sapUom",
            type: "sapUom",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "PO Quantity",
            fieldBinding: "poQuantity",
            fieldLabel: t("poQuantity"),
            type: "poQuantity",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Unit Price",
            fieldBinding: "poUnitPrice",
            fieldLabel: t("poUnitPrice"),
            type: "poUnitPrice",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Net Price",
            fieldBinding: "poTotalAmount",
            fieldLabel: t("poTotalAmount"),
            type: "poTotalAmount",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "PO UOM",
            fieldBinding: "poUom",
            fieldLabel: t("poUom"),
            type: "poUom",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Exception Type",
            fieldBinding: "exceptionType",
            fieldLabel: t("exceptionType"),
            type: "exceptionTypeButton",
            visible: true,
            pinned: false,
          },
        ],
        pendingForApproval: [
          {
            fieldName: "Icon",
            fieldBinding: "exceptionType",
            fieldLabel: "",
            type: "icons",
            visible: true,
            pinned: true,
          },
          {
            fieldName: "S.No",
            fieldBinding: "soItemNumber",
            fieldLabel: t("sNo"),
            type: "sNo",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Item Number",
            fieldBinding: "sapItemNumber",
            fieldLabel: t("sapItemNumber"),
            type: "sapItemNumber",
            visible: true,
            pinned: false,
          },

          {
            fieldName: "Material ID",
            fieldBinding: "poMaterialNumber",
            fieldLabel: t("customerMaterialId"),
            type: "poMaterialNumber",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Material Description",
            fieldBinding: "poMatDescription",
            fieldLabel: t("materialDescription"),
            type: "poMatDescription",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Material ID",
            fieldBinding: "sapMaterialNumber",
            fieldLabel: t("sapMaterialId"),
            type: "sapMaterialNumber",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Material Description",
            fieldBinding: "sapMatDescription",
            fieldLabel: t("sapMaterialDescription"),
            type: "sapMatDescription",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Quantity",
            fieldBinding: "sapQuantity",
            fieldLabel: t("sapQuantity"),
            type: "sapQuantity",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP Unit Price",
            fieldBinding: "sapUnitPrice",
            fieldLabel: "SAP Unit Price",
            type: "sapUnitPrice",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP Net Price",
            fieldBinding: "sapTotalAmount",
            fieldLabel: "SAP Net Price",
            type: "sapTotalPrice",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP UOM",
            fieldBinding: "sapUom",
            fieldLabel: t("sapUom"),
            fieldLabelKey: "sapUom",
            type: "sapUom",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "PO Quantity",
            fieldBinding: "poQuantity",
            fieldLabel: t("poQuantity"),
            type: "poQuantity",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Unit Price",
            fieldBinding: "poUnitPrice",
            fieldLabel: t("poUnitPrice"),
            type: "poUnitPrice",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Net Price",
            fieldBinding: "poTotalAmount",
            fieldLabel: t("poTotalAmount"),
            type: "poTotalAmount",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "PO UOM",
            fieldBinding: "poUom",
            fieldLabel: t("poUom"),
            type: "poUom",
            visible: true,
            pinned: false,
          },

          {
            fieldName: "Exception Type",
            fieldBinding: "exceptionType",
            fieldLabel: t("exceptionType"),
            type: "exceptionTypeButton",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Action",
            fieldBinding: "exceptionType",
            fieldLabel: t("action"),
            type: "action",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Edit",
            fieldBinding: "edit",
            fieldLabel: t("edit"),
            type: "edit",
            visible: true,
            pinned: false,
          },
        ],
        rejected: [
          {
            fieldName: "Icon",
            fieldBinding: "exceptionType",
            fieldLabel: "",
            type: "icons",
            visible: true,
            pinned: true,
          },
          {
            fieldName: "S.No",
            fieldBinding: "soItemNumber",
            fieldLabel: t("sNo"),
            type: "sNo",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Item Number",
            fieldBinding: "sapItemNumber",
            fieldLabel: t("sapItemNumber"),
            type: "sapItemNumber",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Material ID",
            fieldBinding: "poMaterialNumber",
            fieldLabel: t("customerMaterialId"),
            type: "poMaterialNumber",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Material Description",
            fieldBinding: "poMatDescription",
            fieldLabel: t("materialDescription"),
            type: "poMatDescription",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Material ID",
            fieldBinding: "sapMaterialNumber",
            fieldLabel: t("sapMaterialId"),
            type: "sapMaterialNumber",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Material Description",
            fieldBinding: "sapMatDescription",
            fieldLabel: t("sapMaterialDescription"),
            type: "sapMatDescription",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "SAP Quantity",
            fieldBinding: "sapQuantity",
            fieldLabel: t("sapQuantity"),
            type: "sapQuantity",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP Unit Price",
            fieldBinding: "sapUnitPrice",
            fieldLabel: "SAP Unit Price",
            type: "sapUnitPrice",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP Net Price",
            fieldBinding: "sapTotalAmount",
            fieldLabel: "SAP Net Price",
            type: "sapTotalPrice",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "SAP UOM",
            fieldBinding: "sapUom",
            fieldLabel: t("sapUom"),
            fieldLabelKey: "sapUom",
            type: "sapUom",
            visible: false,
            pinned: false,
          },
          {
            fieldName: "PO Quantity",
            fieldBinding: "poQuantity",
            fieldLabel: t("poQuantity"),
            type: "poQuantity",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Unit Price",
            fieldBinding: "poUnitPrice",
            fieldLabel: t("poUnitPrice"),
            type: "poUnitPrice",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Net Price",
            fieldBinding: "poTotalAmount",
            fieldLabel: t("poTotalAmount"),
            type: "poTotalAmount",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "PO UOM",
            fieldBinding: "poUom",
            fieldLabel: t("poUom"),
            type: "poUom",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Exception Type",
            fieldBinding: "exceptionType",
            fieldLabel: t("exceptionType"),
            type: "exceptionTypeButton",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Action",
            fieldBinding: "exceptionType",
            fieldLabel: t("action"),
            type: "action",
            visible: true,
            pinned: false,
          },
          {
            fieldName: "Edit",
            fieldBinding: "edit",
            fieldLabel: t("edit"),
            type: "edit",
            visible: true,
            pinned: false,
          },
        ],

      },
    },
  ];
  const detailScreenHeader = {
    Drafted: t("salesOrderDetailsRequestId"),
    Created: t("salesOrderDetailsOrderId"),
    createdWithBlock: t("salesOrderDetailsOrderId"),
    Cancelled: t("salesOrderDetailsRequestId"),
  };
  const exceptionTypeFields = [
    {
      invalidMaterial: [
        {
          fieldName: "Customer Material ID",
          fieldBinding: "poMaterialNumber",
          fieldLabel: t("CustomerMaterial"),
          visible: true,
        },
        {
          fieldName: "Material Description",
          fieldBinding: "poMatDescription",
          fieldLabel: t("materialDescription"),
          visible: true,
        },
      ],
      materialMaster: [
        {
          fieldName: "Material",
          fieldBinding: "gid",
          fieldLabel: t("material"),
          visible: true,
        },
        {
          fieldName: "Material Description",
          fieldBinding: "globalDescription",
          fieldLabel: t("materialDescription"),
          visible: true,
        },
      ],
      matchedItems: [
        {
          fieldBinding: "checkBox",
          fieldLabel: t(""),
          visible: true,
          type: "checkBox",
        },
        {
          fieldName: "Material",
          fieldBinding: "material",
          fieldLabel: t("material"),
          visible: true,
        },
        {
          fieldName: "Material Description",
          fieldBinding: "materialDescription",
          fieldLabel: t("materialDescription"),
          visible: true,
        },
        {
          fieldName: "Quantity",
          fieldBinding: "quantity",
          fieldLabel: t("quantity"),
          visible: false,
        },
      ],
    },
  ];

  const exceptionTypeTableHeaders = {
    invalidMaterial: t("CustomerPOInvalidmaterial"),
    materialMaster: t("ActiveMaterialList"),
    matchedItems: t("MatchedItems"),
  };
  return {
    modules: modules,
    moduleListFields: moduleListFields,
    detailScreenHeader: detailScreenHeader,
    exceptionTypeFields: exceptionTypeFields,
    exceptionTypeTableHeaders: exceptionTypeTableHeaders,
  };
};
export default applicationConfig;
// config file
