import React from "react";
import {
  Box,
  Chip,
  Tooltip,
  IconButton,
  TextField,
  Stack,
} from "@mui/material";
import EditIcon from "@mui/icons-material/Edit";
import DoneIcon from "@mui/icons-material/Done";
import CancelIcon from "@mui/icons-material/Cancel";
import DeleteOutlinedIcon from "@mui/icons-material/DeleteOutlined";
import CheckCircleOutlineIcon from "@mui/icons-material/CheckCircleOutline";
import DoNotDisturbIcon from "@mui/icons-material/DoNotDisturb";
import EmailIcon from "@mui/icons-material/Email";
import PublicIcon from "@mui/icons-material/Public";
import BusinessIcon from "@mui/icons-material/Business";
import CategoryIcon from "@mui/icons-material/Category";
import AccountTreeIcon from "@mui/icons-material/AccountTree";
import { Switch } from "@cw/rds";

export const getReceiverEmailColumns = (t, handleDelete) => [
  // {
  //   fieldName: "status",
  //   fieldBinding: "status",
  //   fieldLabel: t("Status"),
  //   type: "statusIcon",
  //   visible: true,
  //   width: 100,
  // },
  {
    fieldName: "emailId",
    fieldBinding: "emailId",
    fieldLabel: t("Mail Box Address"),
    visible: true,
    width: 200,
  },
  {
    fieldName: "countryName",
    fieldBinding: "countryName",
    fieldLabel: t("Country"),
    visible: true,
    width: 150,
  },
  {
    fieldName: "salesOrg",
    fieldBinding: "salesOrg",
    fieldLabel: t("Sales Organization"),
    type: "text",
    visible: true,
    width: 120,
  },
  {
    fieldName: "configStatus",
    fieldBinding: "configStatus",
    fieldLabel: t("Azure Status"),
    type: "azureChip",
    visible: true,
    width: 130,
  },

  {
    fieldName: "actions",
    fieldBinding: "actions",
    fieldLabel: t("Action"),
    type: "adminActions",
    visible: true,
    width: 100,
    actionType: "delete",
    onAction: handleDelete,
    deleteKey: "emailId",
  },
];
export const getHanaSyncColumns = (
  t,
  editRowIndex,
  rowDraft,
  handleDraftChange,
  saveEdit,
  cancelEdit,
  startEdit,
  handleDelete,
  editTimezones,
  handleSyncNow
) => {
  return [
    { fieldLabel: t("Country"), fieldBinding: "country", visible: true, width: 150 },
    {
      fieldLabel: t("Hour"),
      fieldBinding: "hour",
      visible: true,
      type: "custom",
      editRowIndex,
      editingData: rowDraft,
      updateDraft: handleDraftChange,
      width: 80,
    },
    {
      fieldLabel: t("Minute"),
      fieldBinding: "minute",
      visible: true,
      type: "custom",
      editRowIndex,
      editingData: rowDraft,
      updateDraft: handleDraftChange,
      width: 80,
    },
    {
      fieldLabel: t("Time Zone"),
      fieldBinding: "timezone",
      visible: true,
      type: "custom",
      editRowIndex,
      editingData: rowDraft,
      editTimezones,
      handleEditChange: handleDraftChange,
      width: 200,
    },
    {
      fieldLabel: t("Status"),
      fieldBinding: "status",
      visible: true,
      type: "adminSwitch",
      editRowIndex,
      rowDraft,
      updateDraft: handleDraftChange,
      width: 100,
    },
    {
      fieldLabel: t("Sync Now"),
      fieldBinding: "sync",
      visible: true,
      type: "custom_btn",
      onAction: handleSyncNow,
      labelText: t("Sync Now"),
      width: 120,
    },
    {
      fieldLabel: t("Actions"),
      fieldBinding: "actions",
      visible: true,
      type: "adminActions",
      actionType: "editSave",
      editRowIndex,
      onEdit: startEdit,
      onSave: saveEdit,
      onCancel: cancelEdit,
      onDelete: handleDelete,
      width: 120,
    },
  ];
};


export const getManualReviewColumns = (
  t,
  editRowIndex,
  rowDraft,
  updateDraft,
  startEdit,
  saveEdit,
  cancelEdit,
  onDelete
) => [
    {
      fieldName: "country",
      fieldBinding: "country",
      fieldLabel: t("Country"),
      visible: true,
      width: 120,
    },
    {
      fieldName: "salesOrg",
      fieldBinding: "salesOrg",
      fieldLabel: t("Sales Organization"),
      visible: true,
      width: 130,
    },
    {
      fieldName: "email",
      fieldBinding: "emailId",
      fieldLabel: t("Email Address"),
      visible: true,
      width: 200,
    },
    {
      fieldName: "emailSchedulerStatus",
      fieldBinding: "emailSchedulerStatus",
      fieldLabel: t("Email Scheduler"),
      type: "adminSwitch",
      visible: true,
      width: 150,
      editRowIndex,
      rowDraft,
      updateDraft,
    },
    {
      fieldName: "manualReviewStatus",
      fieldBinding: "manualReviewStatus",
      fieldLabel: t("Manual Review"),
      type: "adminSwitch",
      visible: true,
      width: 150,
      editRowIndex,
      rowDraft,
      updateDraft,
    },
    {
      fieldName: "frequency",
      fieldBinding: "frequency",
      fieldLabel: t("Frequency(in minutes)"),
      type: "adminEditableNumber",
      visible: true,
      width: 120,
      editRowIndex,
      rowDraft,
      updateDraft,
      minValue: 1,
      step: 1,
      required: true,
    },
    {
      fieldName: "actions",
      fieldBinding: "actions",
      fieldLabel: t("Actions"),
      type: "adminActions",
      visible: true,
      width: 120,
      actionType: "editSave",
      editRowIndex,
      onEdit: startEdit,
      onSave: saveEdit,
      onCancel: cancelEdit,
      onDelete,
    },
  ];


export const getDmsColumns = (
  t,
  editRowIndex,
  editingData,
  editingErrors,
  handleEditChange,
  handleEdit,
  handleSave,
  handleCancelEdit,
  handleDelete,
  editTimezones
) => [
    {
      fieldName: "country",
      fieldBinding: "country",
      fieldLabel: t("Country"),
      visible: true,
      width: 150,
    },
    {
      fieldName: "time",
      fieldBinding: "time",
      fieldLabel: t("Time"),
      type: "custom",
      visible: true,
      width: 120,
      editRowIndex,
      editingData,
      editingErrors,
      handleEditChange,
    },
    {
      fieldName: "weekDay",
      fieldBinding: "weekDay",
      fieldLabel: t("Day"),
      type: "custom",
      visible: true,
      width: 130,
      editRowIndex,
      editingData,
      editingErrors,
      handleEditChange,
    },
    {
      fieldName: "dataRetentionPeriod",
      fieldBinding: "dataRetentionPeriod",
      fieldLabel: t("Data Retention Period (Months)"),
      type: "custom",
      visible: true,
      width: 220,
      editRowIndex,
      editingData,
      editingErrors,
      handleEditChange,
    },
    {
      fieldName: "timezone",
      fieldBinding: "timezone",
      fieldLabel: t("Time Zone"),
      type: "custom",
      visible: true,
      width: 150,
      editRowIndex,
      editingData,
      editingErrors,
      handleEditChange,
      editTimezones,
    },
    {
      fieldName: "actions",
      fieldBinding: "actions",
      fieldLabel: t("Actions"),
      type: "adminActions",
      visible: true,
      width: 120,
      actionType: "editSave",
      editRowIndex,
      onEdit: handleEdit,
      onSave: handleSave,
      onCancel: handleCancelEdit,
      onDelete: handleDelete,
    },
  ];




export const getOrderBlockColumns = (
  t,
  editRowIndex,
  editingData,
  editingErrors,
  handleEditChange,
  handleEdit,
  handleSave,
  handleCancelEdit,
  handleDeleteClick
) => [
    {
      fieldName: "country",
      fieldBinding: "country",
      fieldLabel: "Country",
      visible: true,
      width: 150,
    },
    {
      fieldName: "orderBlock",
      fieldBinding: "orderBlock",
      fieldLabel: "Order Block",
      type: "adminEditableText",
      visible: true,
      width: 150,
      editingData,
      editingErrors,
      handleEditChange,
      maxLength: 2,
    },
    {
      fieldName: "priority",
      fieldBinding: "priority",
      fieldLabel: "Priority",
      type: "adminEditableText",
      visible: true,
      width: 120,
      editRowIndex: editRowIndex,
      editingData,
      editingErrors,
      handleEditChange,
      maxLength: 2,
    },
    {
      fieldName: "orderBlockDesc",
      fieldBinding: "orderBlockDesc",
      fieldLabel: "Description",
      type: "adminEditableText",
      visible: true,
      width: 300,
      editRowIndex: editRowIndex,
      editingData,
      editingErrors,
      handleEditChange,
      multiline: true,
      maxLength: 255,
    },
    {
      fieldName: "actions",
      fieldBinding: "actions",
      fieldLabel: "Actions",
      type: "adminActions",
      visible: true,
      width: 150,
      actionType: "editSave",
      editRowIndex: editRowIndex,
      onEdit: handleEdit,
      onSave: handleSave,
      onCancel: handleCancelEdit,
      onDelete: handleDeleteClick,
    },
  ];

export const getEmailManagementColumns = (t, handleEdit, handleDelete) => [
  {
    fieldName: "emailId",
    fieldBinding: "emailId",
    fieldLabel: "Email Address",
    type: "custom",
    visible: true,
    width: 250,
  },
  {
    fieldName: "country",
    fieldBinding: "country",
    fieldLabel: "Country",
    type: "text",
    visible: true,
    width: 120,
  },
  {
    fieldName: "salesOrg",
    fieldBinding: "salesOrg",
    fieldLabel: "Sales Organization",
    type: "text",
    visible: true,
    width: 130,
  },
  {
    fieldName: "recipientType",
    fieldBinding: "recipientType",
    fieldLabel: "Group",
    type: "custom",
    visible: true,
    width: 120,
  },
  {
    fieldName: "notificationTypes",
    fieldBinding: "notificationTypes",
    fieldLabel: "Notification Types",
    type: "custom",
    visible: true,
    width: 550,
  },
  {
    fieldName: "actions",
    fieldBinding: "actions",
    fieldLabel: "Actions",
    type: "adminActions",
    visible: true,
    width: 120,
    actionType: "delete",
    onAction: handleDelete,
    deleteKey: "id",
  },
];

export const getMaterialConfigColumns = (
  t,
  handleStatusChange,
  handleView,
  handleDownload,
) => [
    {
      fieldLabel: t("Country"),
      fieldBinding: "country",
      visible: true,
      width: 200,
    },
    {
      fieldLabel: t("Sales Organization"),
      fieldBinding: "salesOrg",
      visible: true,
      width: 200,
    },
    {
      fieldLabel: t("Status"),
      fieldBinding: "status",
      visible: true,
      type: "directAdminSwitch",
      onStatusChange: handleStatusChange,
      width: 120,
    },
    {
      fieldLabel: t("Actions"),
      fieldBinding: "actions",
      visible: true,
      type: "documentActions",
      onView: handleView,
      onDownload: handleDownload,
      width: 150,
    },

  ];

export const getCustomerDataConfigColumns = (
  t,
  editRowIndex,
  rowDraft,
  handleDraftChange,
  saveEdit,
  cancelEdit,
  startEdit
) => {
  return [
    {
      fieldLabel: t("Country"),
      fieldBinding: "country",
      visible: true,
      width: 200,
    },
    {
      fieldLabel: t("Sales Organization"),
      fieldBinding: "salesOrg",
      visible: true,
      width: 200,
    },
    {
      fieldLabel: t("Bill To"),
      fieldBinding: "billTo",
      visible: true,
      type: "adminSwitch",
      editRowIndex,
      rowDraft,
      updateDraft: handleDraftChange,
      width: 120,
    },
    {
      fieldLabel: t("Payer To"),
      fieldBinding: "payerTo",
      visible: true,
      type: "adminSwitch",
      editRowIndex,
      rowDraft,
      updateDraft: handleDraftChange,
      width: 120,
    },
    {
      fieldLabel: t("Duplicate PO"),
      fieldBinding: "duplicatePo",
      visible: true,
      type: "adminSwitch",
      editRowIndex,
      rowDraft,
      updateDraft: handleDraftChange,
      width: 120,
    },
    {
      fieldLabel: t("Material Learning"),
      fieldBinding: "materialLearning",
      visible: true,
      type: "adminSwitch",
      editRowIndex,
      rowDraft,
      updateDraft: handleDraftChange,
      width: 100,
    },
    {
      fieldLabel: t("Customer Learning"),
      fieldBinding: "customerLearning",
      visible: true,
      type: "adminSwitch",
      editRowIndex,
      rowDraft,
      updateDraft: handleDraftChange,
      width: 150,
    },
    {
      fieldLabel: t("Actions"),
      fieldBinding: "actions",
      visible: true,
      type: "adminActions",
      actionType: "editSave",
      editRowIndex,
      onEdit: startEdit,
      onSave: saveEdit,
      onCancel: cancelEdit,
      width: 120,
    },
  ];
};
